//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int CancellationId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
